# Generated by Django 3.2.5 on 2021-09-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('entry_date', models.DateTimeField(verbose_name='Entry Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
