# Generated by Django 3.2.5 on 2021-09-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MachineWorks',
            new_name='MachineWork',
        ),
    ]
