# Generated by Django 3.1.13 on 2021-12-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20211227_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinework',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='machinework',
            name='machine_work_type',
            field=models.CharField(choices=[('Planning', 'Planning'), ('Saw', 'Saw'), ('Ripping 1X12 Board', 'Ripping 1X12 Boards'), ('2X6 & 2X8 wood', '2X6 & 2X8 wood'), ('Beam 3X12', 'Beam 3X12'), ('Beam 4X12', 'Beam 4X12'), ('Wabire & Asemfra', 'Wabire & Asemfra'), ('Bed Machine', 'Bed Machine'), ('Door', 'Door'), ('Door Gate', 'Door Gate'), ('Ban-Saw', 'Ban-Saw'), ('Mono Desk', 'Mono Desk'), ('Door and Cramping', 'Door and Cramping'), ('Frame Plaining 3 in 1', 'Frame Plaining 3 in 1'), ('2 in 1 & Door Frame', '2 in 1 & Door Frame')], max_length=30),
        ),
    ]
