# Generated by Django 3.1.13 on 2021-12-31 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20211231_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinework',
            name='description',
        ),
    ]
