# Generated by Django 4.0 on 2022-01-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_furnitureitempurchase_furniturepurchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniturepurchase',
            name='total_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
