# Generated by Django 4.0 on 2022-01-20 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_furnituresupply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniturepurchase',
            name='customer',
        ),
    ]
