# Generated by Django 4.0 on 2022-01-21 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_remove_furniturepurchase_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='WoodItemSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='woodfrombush',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='woodsale',
            name='log',
        ),
        migrations.RemoveField(
            model_name='woodsale',
            name='quantity',
        ),
        migrations.AddField(
            model_name='woodsale',
            name='woodfrombush',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.woodfrombush'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salary',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.AddField(
            model_name='wooditemsale',
            name='woodfrombush',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.woodfrombush'),
        ),
        migrations.AddField(
            model_name='wooditemsale',
            name='woodsale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.woodsale', verbose_name='woodsale'),
        ),
    ]
