# Generated by Django 4.0 on 2022-01-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_wooditemsale_remove_woodfrombush_processed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='woodfrombush',
            name='woodtype',
        ),
        migrations.AddField(
            model_name='woodfrombush',
            name='description',
            field=models.CharField(choices=[('2 X 4', '2 X 4'), ('2 X 6', '2 X 6'), ('2 X 8', '2 X 8'), ('2 X 2', '2 X 2'), ('1 X 9', '1 X 9'), ('1 X 10', '1 X 10'), ('1 X 12', '1 X 12'), ('Wawa Board', 'Wawa Board'), ('Nyamedua', 'Nyamedua'), ('Saba', 'Saba'), ('Ceiling Buttons', 'Ceiling Buttons')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
