# Generated by Django 4.0 on 2022-01-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_remove_woodfrombush_woodtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='woodsale',
            name='woodfrombush',
        ),
        migrations.AlterField(
            model_name='woodsale',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
