# Generated by Django 4.0 on 2022-01-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_remove_woodsale_woodfrombush_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='woodsale',
            name='customer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
