# Generated by Django 4.0 on 2022-01-25 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_woodsale_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='woodsale',
            name='customer',
        ),
    ]
