# Generated by Django 4.0 on 2022-01-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_remove_woodsale_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='woodfrombush',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
