# Generated by Django 4.0 on 2022-01-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_furnituresupply_date_recorded_wooditemsale_date_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='woodfrombush',
            name='profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
