# Generated by Django 4.0 on 2022-02-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_woodfrombush_profit_margin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='woodfrombush',
            name='profit_margin',
        ),
    ]
