# Generated by Django 3.1.13 on 2021-12-23 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otherNames', models.CharField(max_length=50)),
                ('hometown', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('emergencyContactPerson', models.CharField(max_length=50)),
                ('emergencyContactNumber', models.CharField(max_length=10)),
                ('picture', models.ImageField(upload_to='profile/')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-user',),
            },
        ),
    ]
