# Generated by Django 3.1.13 on 2022-01-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220107_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='emergencyContactNumber',
            new_name='emergency_contact_number',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='emergencyContactPerson',
            new_name='emergency_contact_person',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='otherNames',
        ),
        migrations.AddField(
            model_name='staff',
            name='other_names',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
