# Generated by Django 3.1.13 on 2022-01-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220110_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='other_names',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
